In [1]:
import pandas as pd

In [2]:
a = pd.read_csv('STG_MVT_CRD_csv.csv')

In [3]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID_STG_MVT_CRD       15 non-null     int64  
 1   VLR_SDO_UTZ_CRD_RTO  1 non-null      float64
 2   VLR_TOT_FAT          1 non-null      float64
 3   VLR_MIM_FAT          1 non-null      float64
 4   VLR_PCL_FAT          13 non-null     float64
 5   QTD_CLI_CAD_POS      15 non-null     int64  
 6   QTD_MVT              15 non-null     int64  
 7   DES_TIP_PSS          15 non-null     object 
 8   ID_FNT_ITT           15 non-null     int64  
 9   COD_MDL              15 non-null     object 
 10  DAT_RSS_FNT_ITT      15 non-null     object 
 11  DAT_INC_DBO          15 non-null     object 
dtypes: float64(4), int64(4), object(4)
memory usage: 1.5+ KB


In [4]:
a['DAT_RSS_FNT_ITT'] = pd.to_datetime(a['DAT_RSS_FNT_ITT'])

In [5]:
a['DAT_INC_DBO'] = pd.to_datetime(a['DAT_INC_DBO'])

In [6]:
#coluna 1, verifica quantos valores nulos há
b = a['VLR_SDO_UTZ_CRD_RTO'].isnull().value_counts()
b

True     14
False     1
Name: VLR_SDO_UTZ_CRD_RTO, dtype: int64

In [7]:
#coluna 2, verifica quantos valores nulos há
c = a['VLR_TOT_FAT'].isnull().value_counts()
c

True     14
False     1
Name: VLR_TOT_FAT, dtype: int64

In [8]:
#coluna 3, verifica quantos valores nulos há
d = a['VLR_MIM_FAT'].isnull().value_counts()
d

True     14
False     1
Name: VLR_MIM_FAT, dtype: int64

In [9]:
#coluna 4, verifica quantos valores nulos há
e = a['VLR_PCL_FAT'].isnull().value_counts()
e

False    13
True      2
Name: VLR_PCL_FAT, dtype: int64

In [10]:
#coluna 1, verifica se há zeros(0)
a[a['VLR_SDO_UTZ_CRD_RTO'] == 0]

Empty DataFrame
Columns: [ID_STG_MVT_CRD, VLR_SDO_UTZ_CRD_RTO, VLR_TOT_FAT, VLR_MIM_FAT, VLR_PCL_FAT, QTD_CLI_CAD_POS, QTD_MVT, DES_TIP_PSS, ID_FNT_ITT, COD_MDL, DAT_RSS_FNT_ITT, DAT_INC_DBO]
Index: []

In [11]:
#coluna 2, verifica se há zeros(0)
a[a['VLR_TOT_FAT'] == 0]

Empty DataFrame
Columns: [ID_STG_MVT_CRD, VLR_SDO_UTZ_CRD_RTO, VLR_TOT_FAT, VLR_MIM_FAT, VLR_PCL_FAT, QTD_CLI_CAD_POS, QTD_MVT, DES_TIP_PSS, ID_FNT_ITT, COD_MDL, DAT_RSS_FNT_ITT, DAT_INC_DBO]
Index: []

In [12]:
#coluna 3, verifica se há zeros(0)
a[a['VLR_MIM_FAT'] == 0]

Empty DataFrame
Columns: [ID_STG_MVT_CRD, VLR_SDO_UTZ_CRD_RTO, VLR_TOT_FAT, VLR_MIM_FAT, VLR_PCL_FAT, QTD_CLI_CAD_POS, QTD_MVT, DES_TIP_PSS, ID_FNT_ITT, COD_MDL, DAT_RSS_FNT_ITT, DAT_INC_DBO]
Index: []

In [13]:
#coluna 4, verifica se há zeros(0)
a[a['VLR_PCL_FAT'] == 0]

Empty DataFrame
Columns: [ID_STG_MVT_CRD, VLR_SDO_UTZ_CRD_RTO, VLR_TOT_FAT, VLR_MIM_FAT, VLR_PCL_FAT, QTD_CLI_CAD_POS, QTD_MVT, DES_TIP_PSS, ID_FNT_ITT, COD_MDL, DAT_RSS_FNT_ITT, DAT_INC_DBO]
Index: []

In [14]:
a1 = pd.read_csv('a1_STG_MVT_CRD_csv.csv')

In [15]:
a1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID_STG_MVT_CRD       15 non-null     int64 
 1   VLR_SDO_UTZ_CRD_RTO  15 non-null     int64 
 2   VLR_TOT_FAT          15 non-null     int64 
 3   VLR_MIM_FAT          15 non-null     int64 
 4   VLR_PCL_FAT          15 non-null     int64 
 5   QTD_CLI_CAD_POS      15 non-null     int64 
 6   QTD_MVT              15 non-null     int64 
 7   DES_TIP_PSS          15 non-null     object
 8   ID_FNT_ITT           15 non-null     int64 
 9   COD_MDL              15 non-null     object
 10  DAT_RSS_FNT_ITT      15 non-null     object
 11  DAT_INC_DBO          15 non-null     object
dtypes: int64(8), object(4)
memory usage: 1.5+ KB


In [16]:
a1['DAT_RSS_FNT_ITT'] = pd.to_datetime(a1['DAT_RSS_FNT_ITT'])

In [17]:
a1['DAT_INC_DBO'] = pd.to_datetime(a1['DAT_INC_DBO'])

In [18]:
a1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_STG_MVT_CRD       15 non-null     int64         
 1   VLR_SDO_UTZ_CRD_RTO  15 non-null     int64         
 2   VLR_TOT_FAT          15 non-null     int64         
 3   VLR_MIM_FAT          15 non-null     int64         
 4   VLR_PCL_FAT          15 non-null     int64         
 5   QTD_CLI_CAD_POS      15 non-null     int64         
 6   QTD_MVT              15 non-null     int64         
 7   DES_TIP_PSS          15 non-null     object        
 8   ID_FNT_ITT           15 non-null     int64         
 9   COD_MDL              15 non-null     object        
 10  DAT_RSS_FNT_ITT      15 non-null     datetime64[ns]
 11  DAT_INC_DBO          15 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(8), object(2)
memory usage: 1.5+ KB


In [19]:
#todos os valores da col 7 são o mesmo
a1['DES_TIP_PSS'].is_unique

False

In [20]:
#coluna 9
a1['COD_MDL'].is_unique

True

In [21]:
#coluna 0
a1['ID_STG_MVT_CRD'].is_unique

True

In [22]:
#coluna 1
a1['VLR_SDO_UTZ_CRD_RTO'].is_unique

False

In [23]:
#coluna 2
a1['VLR_TOT_FAT'].is_unique

False

In [24]:
#coluna 3
a1['VLR_MIM_FAT'].is_unique

False

In [25]:
#coluna 4
a1['VLR_PCL_FAT'].is_unique

False

In [26]:
#coluna 5
a1['QTD_CLI_CAD_POS'].is_unique

True

In [27]:
#coluna 6
a1['QTD_MVT'].is_unique

True

In [28]:
#coluna 8
a1['ID_FNT_ITT'].is_unique

False

In [29]:
#coluna 10
a1['DAT_RSS_FNT_ITT'].is_unique

False

In [30]:
#coluna 11
a1['DAT_INC_DBO'].is_unique

False

In [31]:
a1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_STG_MVT_CRD       15 non-null     int64         
 1   VLR_SDO_UTZ_CRD_RTO  15 non-null     int64         
 2   VLR_TOT_FAT          15 non-null     int64         
 3   VLR_MIM_FAT          15 non-null     int64         
 4   VLR_PCL_FAT          15 non-null     int64         
 5   QTD_CLI_CAD_POS      15 non-null     int64         
 6   QTD_MVT              15 non-null     int64         
 7   DES_TIP_PSS          15 non-null     object        
 8   ID_FNT_ITT           15 non-null     int64         
 9   COD_MDL              15 non-null     object        
 10  DAT_RSS_FNT_ITT      15 non-null     datetime64[ns]
 11  DAT_INC_DBO          15 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(8), object(2)
memory usage: 1.5+ KB


In [34]:
#coluna 1
a1['VLR_SDO_UTZ_CRD_RTO'].value_counts().values

array([14,  1], dtype=int64)

In [35]:
#coluna 2
a1['VLR_TOT_FAT'].value_counts().values

array([14,  1], dtype=int64)

In [36]:
#coluna 3
a1['VLR_MIM_FAT'].value_counts().values

array([14,  1], dtype=int64)

In [37]:
#coluna 4, tirando as valores nulos, todos são exclusivos.
a1['VLR_PCL_FAT'].value_counts().values

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)